# Generated by Django 6.0.6 on 2026-06-22 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('patient_history', 'Patient Visit History'), ('doctor_performance', 'Doctor Performance'), ('appointment_summary', 'Appointment Summary')], max_length=25)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Filters used to generate this report')),
                ('data', models.JSONField(help_text='The computed report payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
